WIPE_SPEED : int = 50
WIPE_CLEAR_DELAY : int = 10
GAMEOVER_WIPE_COLOR : str = "red"

QUESTION_X_POS : int = -350
QUESTION_Y_POS : int = 100
ANSWER_Y_OFFSET : int = 50

BANNER_Y_POS : int = 330
BANNER_X_BOUND : int = 1200